### ISSUE TITLE
Unnecessary warnings and errors in console

### ISSUE THREAD

**Issue by os-tohe** [stellR42/vue3-pdf-app#13]
#### Configuration:
- Web browser and it`s version: Chrome Version 116.0.5845.187 (Official Build) (64-bit)
- Operating system and it`s version: Windows 10 Pro Version 22H2
- vue-pdf-app version: 1.0.3

#### Steps to reproduce the problem:
Just import and use the component like this:
```Vue
<template>
  <VuePdfApp pdf="http://localhost:3000/example.pdf" style="height: 100vh" />
</template>

<script setup lang="ts">
import VuePdfApp from 'vue3-pdf-app'
</script>
```

#### What is the expected behavior?
No warnings or errors or other unnecessary logs in console.

#### What went wrong?
Console shows these logs:
- using the embedded JSON directory, early way out (l10n.js:306)
- argument {{progress}} for #print_progress_percent is undefined. (l10n.js:883)
- Warning: Setting up fake worker. (util.js:358)

This warning:
- could not parse arguments for #print_progress_percent (l10n.js:93)

And this error:
- GET http://localhost:3000/printout/img/loading-icon.2cb588dc.svg 404 (Not Found)

#### Attachments (screenshots, links, etc)
![image](https://github.com/stellR42/vue3-pdf-app/assets/126565419/3abff11c-66c5-4331-9dc5-76daf1e0caae)

#### Other information
The same logs occur if I import the pdf from ArrayBuffer. These logs are the only thing preventing us from using this package in our app.

**Comment by rutup** [comment]
Is there any update on this issue?

**Comment by Joey-Gr** [comment]
I also have the same issue. I think someone forked a tempory correction on the arguments part in the meantime here: https://github.com/stellR42/vue3-pdf-app/compare/master...chenjin01:vue3-pdf-app:master

however for the images and img (There's the loading-icon in the "img" directory, and the annotation image icons in "images" directory for some reason ). 

It seems to be trying to find the images inside of your public folder, "img/loading-icon", so just putting the images in question there should work. But for me (using nuxt3), when I try to use it in a page, it will use the path of the page itself, even though it shouldn't like in a product details page, it goes "product/img/loading-icon...". So something is definitely not right there.

Edit:

> it will use the path of the page itself, even though it shouldn't like in a login page, it goes "product/img/loading-icon...".

For me at least, this problem only happens if I'm at least 2 pages deep. (Like "/product/2"), if I want to show the pdf there, there is that "img" problem, and it will specifically go to "{{host}}/product/img", kind of like when you do "../img/loading-icon.svg"

**Comment by Joey-Gr** [comment]
Bumping this because the issue has not yet been resolved. Or if it is, it is not fully understood by the users.

I feel like this is an issue with the path using the ones in the root of the project rather than in the node_modules. I'm using Nuxt, not sure if it makes a difference here.
