### ISSUE TITLE
how to disabled keyevent such as ctrl+s

### ISSUE THREAD

**Issue by awesomeric** [stellR42/vue3-pdf-app#23]
**Please describe a feature/problem.**
how to disabled keyevent such as ctrl+s

**Describe the solution you'd like**
no such api

**Describe alternatives you've considered**
added a config to do that?

**Additional context**

**Comment by remiebelingmerifond** [comment]
I had a simliar problem.
I needed to prevent users from Printing and downloading the PDD-File using Keyboard-Shortcuts.

Since i was not able to find any suitable config values, i ended up with a kinda hacky "Solution". 
Not nice, but it seems to do the trick for now...

@awesomeric just in case you – or anyone else, are still looking for a workaround, here is what i came up with:

```vue
<vue-pdf-app
    style="height: 100vh;"
    :pdf="pdfSrc"
    @pages-rendered="pagesRendered"  
    />
```
```js
pagesRendered (pdfLib) {
    pdfLib.unbindWindowEvents();
}
```
